// ReSharper disable InconsistentNaming
namespace CleanArchitectureBase.Domain.Constants;

public static class ErrorCodes
{
    //COMMON
    public const string COMMON_FORBIDDEN = nameof(COMMON_FORBIDDEN);
    public const string COMMON_SERVER_INTERNAL_ERROR = nameof(COMMON_SERVER_INTERNAL_ERROR);
    public const string COMMON_NOT_FOUND = nameof(COMMON_NOT_FOUND);
    public const string COMMON_GONE = nameof(COMMON_GONE);
    public const string COMMON_BAD_REQUEST = nameof(COMMON_BAD_REQUEST);
    public const string COMMON_CONFLICT = nameof(COMMON_CONFLICT);
    public const string COMMON_TIMEOUT_ERROR = nameof(COMMON_TIMEOUT_ERROR);

    //ACCOUNT
    public const string ACCOUNT_NOTFOUND = nameof(ACCOUNT_NOTFOUND);
    public const string ACCOUNT_LOCKED = nameof(ACCOUNT_LOCKED);
    public const string ACCOUNT_BANNED = nameof(ACCOUNT_BANNED);
    public const string ACCOUNT_USERNAME_ALREADY_EXISTS = nameof(ACCOUNT_USERNAME_ALREADY_EXISTS);
    public const string ACCOUNT_EMAIL_ALREADY_EXISTS = nameof(ACCOUNT_EMAIL_ALREADY_EXISTS);
    public const string ACCOUNT_INVALID_PASSWORD = nameof(ACCOUNT_INVALID_PASSWORD);
    public const string ACCOUNT_INVALID_CREDENTIALS = nameof(ACCOUNT_INVALID_CREDENTIALS);
    public const string ACCOUNT_INVALID_VERIFICATION_CODE = nameof(ACCOUNT_INVALID_VERIFICATION_CODE);
    
    
    //IDENTITY OVERRIDE ERROR DESCRIBER
    public const string IDENTITY_DEFAULT_ERROR = nameof(IDENTITY_DEFAULT_ERROR);
    public const string IDENTITY_CONCURRENCY_FAILURE = nameof(IDENTITY_CONCURRENCY_FAILURE);
    public const string IDENTITY_PASSWORD_MISMATCH = nameof(IDENTITY_PASSWORD_MISMATCH);
    public const string IDENTITY_INVALID_TOKEN = nameof(IDENTITY_INVALID_TOKEN);
    public const string IDENTITY_RECOVERY_CODE_REDEMPTION_FAILED = nameof(IDENTITY_RECOVERY_CODE_REDEMPTION_FAILED);
    public const string IDENTITY_LOGIN_ALREADY_ASSOCIATED = nameof(IDENTITY_LOGIN_ALREADY_ASSOCIATED);
    public const string IDENTITY_INVALID_USER_NAME = nameof(IDENTITY_INVALID_USER_NAME);
    public const string IDENTITY_INVALID_EMAIL = nameof(IDENTITY_INVALID_EMAIL);
    public const string IDENTITY_DUPLICATE_USER_NAME = nameof(IDENTITY_DUPLICATE_USER_NAME);
    public const string IDENTITY_DUPLICATE_EMAIL = nameof(IDENTITY_DUPLICATE_EMAIL);
    public const string IDENTITY_INVALID_ROLE_NAME = nameof(IDENTITY_INVALID_ROLE_NAME);
    public const string IDENTITY_DUPLICATE_ROLE_NAME = nameof(IDENTITY_DUPLICATE_ROLE_NAME);
    public const string IDENTITY_USER_ALREADY_HAS_PASSWORD = nameof(IDENTITY_USER_ALREADY_HAS_PASSWORD);
    public const string IDENTITY_USER_LOCKOUT_NOT_ENABLED = nameof(IDENTITY_USER_LOCKOUT_NOT_ENABLED);
    public const string IDENTITY_USER_ALREADY_IN_ROLE = nameof(IDENTITY_USER_ALREADY_IN_ROLE);
    public const string IDENTITY_USER_NOT_IN_ROLE = nameof(IDENTITY_USER_NOT_IN_ROLE);
    public const string IDENTITY_PASSWORD_TOO_SHORT = nameof(IDENTITY_PASSWORD_TOO_SHORT);
    public const string IDENTITY_PASSWORD_REQUIRES_UNIQUE_CHARS = nameof(IDENTITY_PASSWORD_REQUIRES_UNIQUE_CHARS);
    public const string IDENTITY_PASSWORD_REQUIRES_NON_ALPHANUMERIC = nameof(IDENTITY_PASSWORD_REQUIRES_NON_ALPHANUMERIC);
    public const string IDENTITY_PASSWORD_REQUIRES_DIGIT = nameof(IDENTITY_PASSWORD_REQUIRES_DIGIT);
    public const string IDENTITY_PASSWORD_REQUIRES_LOWER = nameof(IDENTITY_PASSWORD_REQUIRES_LOWER);
    public const string IDENTITY_PASSWORD_REQUIRES_UPPER = nameof(IDENTITY_PASSWORD_REQUIRES_UPPER);

}
